config/routes.rb
Rails.application.routes.draw do
 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'pages#home'

get 'pages/about', to:'pages#about'

resources :articles



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

#     validates  :title , presence :true,length: {minimum:3, maximum:50}
# validates  :description, presence :true,length: {minimum:10, maximum:500}
validates :title, presence: true,length: {minimum:3, maximum:50}
validates  :description, presence: true,length: {minimum:10, maximum:500}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


    def index

        @articles = Article.all

    end     

    def  new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
    

        if @article.save
            #do something
            flash[:notice]="New Article created"
            redirect_to article_path(@article)
        else 
             render 'new'
        end     
            
        

    end  
    
    
    def edit
        @article = Article.find(params[:id])

    end    


    def update 
        @article = Article.find(params[:id])

        if @article.update(article_params)
            flash[:notice]=" Article updated"
            redirect_to article_path(@article)

        else 
            render 'edit'


        end    
            

    end    

    def show

        @article = Article.find(params[:id])

    end    



    def destroy

        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice]=" Article Deleted"
        redirect_to articles_path
         


    end    

    private 
        def article_params
            params.require(:article).permit(:title,:description)
        end     


end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end    


    def about 

    end   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following error affetcted the article</h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>

<li><%= msg %></li>


<% end %>

</ul>

<% end %>


<%= form_for  @article do |f| %>

<p>
<%= f.label :title %><br />

<%= f.text_field :title%>
</p>

<p>
<%= f.label :description %><br />

<%= f.text_area  :description %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

 <%= link_to "back home", articles_path %>

app/views/articles/edit.html.erb
<h2>Edit Form</h2>
 
 <%= render 'form' %>

 <%= link_to="back home",article_path%>

app/views/articles/index.html.erb
<h3>List all article</h3>
<%= link_to 'create Article', new_article_path %>
<table>

<tr>

<th>title</th>
<th>description</th>
<th>more</th>

</tr>
<% @articles.each do |article| %>

<tr>
<th><%= article.title %></th>
<th><%= article.description %></th>
<th><%= link_to 'Edit', edit_article_path(article)  %></th>
<th><%= link_to 'show', article_path(article) %></th>
<th> <%= link_to 'Delete', article_path(article), method: :delete  %></th>

</tr>
<% end %>

</table>

app/views/articles/new.html.erb
<h2>Create an article</h2>
 <%= render 'form' %>

app/views/articles/show.html.erb
<h2>show seleted artile</h2>
 <%= link_to "back home", articles_path %>

<p>Tile:<%= @article.title %></p>


<p>Description:<%= @article.description %></p>

app/views/layouts/_message.html.erb
  <% flash.each do |name,msg| %>

  <ul>
  <li><%= msg %>

  </li>
  </ul>


  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h3>Welcome to about<h3>


<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Hello World <h1>




<%= link_to 'About', pages_about_path %>